#define ID_MAIN                     100
#define ID_HEX                      101
#define ID_HEXSWAP                  102
#define ID_VALUE                    103
#define ID_HEXTITLE                 104
#define ID_HEXSWAPTITLE             105
#define ID_VALUETITLE               106
#define ID_ICON                     107
#define ID_MENU                     108
#define ID_FILE                     109
#define ID_EXIT                     110
#define ID_VIEW                     112
#define ID_SHORT                    113
#define ID_LONG                     114
#define ID_FLOAT                    115
#define ID_DOUBLE                   116
#define ID_STAT                     117
#define ID_LDOUBLE                  118
#define ID_HELPMENU                 119
#define ID_ABOUTOPTION              120
#define ID_HELPOPTION               121
#define ID_ABOUT                    200
#define ID_ABOUT2                   201
#define ID_ABOUT1                   202
#define ID_ABOUT3                   203
#define ID_ABOUT_OK                 204
#define ID_HELP                     300
#define ID_HELP_OK                  301
#define ID_HELP1                    302
#define ID_HELP2                    303
#define ID_HELP3                    304
#define ID_HELP4                    305
